# Generated by Django 3.2.18 on 2023-05-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='categories',
        ),
    ]
